[ENG-1327] Patched Magento for MariaDB 10.5 and added 2.4.4
nexcess/app-sources pull request #54
Opened 2022-06-03 14:20 UTC by JamesColeman-LW

This includes patches for MariaDB 10.5 in the `di.xml` file at `app/etc/di.xml` and `vendor/magento/magento2-base/app/etc/di.xml` and adds Magento 2.4.4.

<details><summary>View patch script</summary>
<p>

This is the patch script used to patch Magento's di.xml

```bash
#!/bin/bash
for MAGE in Magento-CE-*.tar.gz; do
    echo "Patching $MAGE"
    mkdir tmp
    cd tmp
    tar -xzf ../$MAGE
    if [ -f ./app/etc/di.xml ]; then
        if grep -q MariaDB ./app/etc/di.xml; then
            sed -i 's/MariaDB-(10\.[0-9]-10\.[0-9])" xsi:type="string">^10\\\.\[[0-9-]\+]/MariaDB-(10.2-10.5)" xsi:type="string">^10\\.[2-5]/' ./app/etc/di.xml
        else
            echo "No MariaDB version checking in this version."
            cd ../
            rm -Rf tmp
            continue
        fi
    else
        echo "Failed to patch: $MAGE"
        exit
    fi
    if [ -f ./vendor/magento/magento2-base/app/etc/di.xml ]; then
        if grep -q MariaDB ./vendor/magento/magento2-base/app/etc/di.xml; then
            sed -i 's/MariaDB-(10\.[0-9]-10\.[0-9])" xsi:type="string">^10\\\.\[[0-9-]\+]/MariaDB-(10.2-10.5)" xsi:type="string">^10\\.[2-5]/' ./vendor/magento/magento2-base/app/etc/di.xml
        fi
    else
        echo "Failed to patch magento2-base: $MAGE"
        exit
    fi

    tar -czf ../$MAGE .
    cd ../
    rm -Rf tmp
    MD5=$(md5sum $MAGE | awk '{print $1}')
    echo "Old MD5:" $(cat $MAGE.md5)
    echo "New MD5: $MD5"
    echo $MD5 > $MAGE.md5
done
```

</p>
</details>

2022-06-03 14:34 UTC, rfxn approved these changes

2022-06-06 15:26 UTC, ChrisOrlando requested changes

2022-06-06 15:26 UTC, ChrisOrlando commented on magento/2/latest-version
> -2.4.2
this change has the consequence of bumping the version of magento we auto-install, let's not do that in this PR.

2022-06-06 15:26 UTC, ChrisOrlando commented on magento/2/latest-tarball
> -Magento-CE-2.4.2.tar.gz
same here, bumps version

2022-06-06 15:33 UTC, JamesColeman-LW commented on magento/2/latest-tarball
> -Magento-CE-2.4.2.tar.gz
Removed the commit that bumps version, I'll create another jira ticket for that and another pull request.

2022-06-06 16:10 UTC, ChrisOrlando approved these changes

2022-06-27 15:25 UTC, merged